---

- hosts: all
  become: true
  tasks:

  - name: update repository index for apt based systems
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: update repository index for dfn based systems
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php package for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]


