---

- hosts: all
  become: true
  tasks:

  - name: update repository and install apache2 and php package for apt devices
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: update repository and install apache2 and php package for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["CentOS"]


