---

- hosts: Test, Raspi, CentOS, fileservers
  become: true
  tasks:

  - name: Shutdown Debian and CentOS base machines
    command: shutdown -P
    when: ansible_distribution in ["Debian", "Ubuntu", "CentOS"]

