---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["CentOS"]

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu"]

  - name: update repo cache (PiOS)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian"]


- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH8oaUz8ddX8inB9sgv3VhYUWLVJUD+6tJIhydkmUtEG ansible"


#- hosts: workstations
#  become: true
#  tasks:
#
#  - name: install unzip
#    package:
#      name: unzip
#
#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
#      dest: /usr/local/bin
#      remote_src: yes
#      mode: 0755
#      owner: root
#      group: root


- hosts: webservers
  become: true
  tasks:

  - name: install apache2 and php package for apt devices
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 and php package for CentOS
    tags: apache,httpd,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes 
    when: ansible_distribution in ["CentOS"]

  - name: change e-mail address for admin in apache (CentOS)
    tags: appache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd_var

  - name: restart httpd (CentOS)
    tags: appache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd_var.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: Raspi
  become: true
  tasks:

  - name: remove apache2 and php package for apt devices
    tags: rmapache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install mariadb package
    tags: db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: fileservers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "CentOS"]
