---


- hosts: all
  become: true
  tasks:

  - name: update PiOS and Ubuntu repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: upgrade PiOS
    apt:
      upgrade: yes
    when: ansible_distribution == "Debian" and ansible_distribution_version == "10"

  - name: upgrade Ubuntu     
    apt:
      upgrade: full
    when: ansible_distribution == "Ubuntu"


