- name: install unzip
  package:
    name: unzip

#  - name: install terraform
#    unarchive:
#      src: https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_li>
#      dest: /usr/local/bin
#      remote_src: yes
#      owner: root
#      group: root
#      mode: 0755
